//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SysMenus
    {
        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuIcon { get; set; }
        public string ParentId { get; set; }
        public int SortNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public bool IsDeleted { get; set; }
        public string MenuUrl { get; set; }
        public bool Islink { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ParentMenuName { get; set; }
    }
}
