//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XT_User
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string PersonType { get; set; }
        public string SpellHead { get; set; }
        public string OrgCode { get; set; }
        public string Gender { get; set; }
        public string IdcardTypeId { get; set; }
        public string IdcardType { get; set; }
        public string IdcardNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> JoinCompanyDate { get; set; }
        public string PhoneOffice { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneMobile { get; set; }
        public string IfActivation { get; set; }
        public string EmailInside { get; set; }
        public string EmailOutside { get; set; }
        public string PostCode { get; set; }
        public string PostName { get; set; }
        public string PostLevelId { get; set; }
        public string PostLevel { get; set; }
        public string PostTrueLevel { get; set; }
        public string WorkStatusId { get; set; }
        public string WorkStatus { get; set; }
        public Nullable<decimal> SortCode { get; set; }
        public string LoginPermissions { get; set; }
        public string LoginPassword { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> TheLoginTime { get; set; }
        public Nullable<decimal> TotalLoginCount { get; set; }
        public string IfSyn { get; set; }
        public string YGDBLevel { get; set; }
        public string QAGLevel { get; set; }
        public string Party { get; set; }
        public string EducationId { get; set; }
        public string IfSmoke { get; set; }
        public string Hobby { get; set; }
        public string History { get; set; }
        public string Remark { get; set; }
        public string ExpandOne { get; set; }
        public string ExpandTwo { get; set; }
        public string ExpandThree { get; set; }
        public string ExpandFour { get; set; }
        public string ExpandFive { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
