//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XT_OperateLog
    {
        public string OperateId { get; set; }
        public string RelevanceId { get; set; }
        public string Fromtable { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string OrgCode { get; set; }
        public string InternalHierarchyName { get; set; }
        public string OperateType { get; set; }
        public string DetailSrc { get; set; }
        public string DeviceType { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public string CreateByEmpName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public string ModifyByEmpName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
