//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YH_HiddenDanger
    {
        public string HiddenDangerId { get; set; }
        public decimal SerialNo { get; set; }
        public string OrgCode { get; set; }
        public string ResponsOrg { get; set; }
        public string FindEmpCode { get; set; }
        public string FindEmpName { get; set; }
        public Nullable<System.DateTime> FindTime { get; set; }
        public string CheckOrgCode { get; set; }
        public string NoSafetyActionId { get; set; }
        public string NoSafetyStatusId { get; set; }
        public string IsManageDefect { get; set; }
        public string CategoryId { get; set; }
        public string CategoryHierarchyName { get; set; }
        public string ProCategory { get; set; }
        public string ProCategoryHierarchyName { get; set; }
        public string HiddenContent { get; set; }
        public string IfNeedAnalysis { get; set; }
        public string RectifyWay { get; set; }
        public string Measure { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public string MakePerson { get; set; }
        public Nullable<System.DateTime> MakeTime { get; set; }
        public string RectifySituation { get; set; }
        public string UnRectifyReason { get; set; }
        public string UnAcceptReason { get; set; }
        public string FeedbackEmpCode { get; set; }
        public string FeedbackEmpName { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public Nullable<decimal> RectifyTimes { get; set; }
        public string CurrentEmpCode { get; set; }
        public string CurrentEmpName { get; set; }
        public string CurrentStatus { get; set; }
        public string LastStatus { get; set; }
        public Nullable<decimal> PenaltyPoint { get; set; }
        public string PointRemark { get; set; }
        public string IfActivity { get; set; }
        public string FromTable { get; set; }
        public string RelevanceId { get; set; }
        public string HiddenGradefactor { get; set; }
        public string HiddenGrade { get; set; }
        public string MaybeResult { get; set; }
        public string HiddenParts { get; set; }
        public Nullable<decimal> CorrectiveAmount { get; set; }
        public Nullable<System.DateTime> DelayedDateBefore { get; set; }
        public Nullable<System.DateTime> DelayedDate { get; set; }
        public string DelayedTempMeasure { get; set; }
        public string DelayedReasons { get; set; }
        public string DelayedStatus { get; set; }
        public string IfSafetyHazard { get; set; }
        public string NotAcceptStatus { get; set; }
        public string NotAcceptReason { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string SpecialHiddenId { get; set; }
        public string SpecialHiddenName { get; set; }
        public Nullable<bool> IsHaveWXHazard { get; set; }
        public Nullable<bool> IsPerfectWXHazard { get; set; }
        public string ReasonRemark { get; set; }
        public string CreateByEmpCode { get; set; }
        public string CreateByEmpName { get; set; }
        public string ModifyByEmpCode { get; set; }
        public string ModifyByEmpName { get; set; }
        public string OrgCodeIHName { get; set; }
        public string CheckOrgIHName { get; set; }
        public string ResponsOrgIHName { get; set; }
    }
}
