//------------------------------------------------------------------------------
    // <auto-generated>
    //    此代码是根据模板生成的。
    //
    //    手动更改此文件可能会导致应用程序中发生异常行为。
    //    如果重新生成代码，则将覆盖对此文件的手动更改。
    // </auto-generated>
    //------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Office.Data.Models;
    namespace Office.Data
    {
        public partial class WechatEntities : DbContext
        {
            public WechatEntities()
                : base("name=WechatEntities")
            {
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                //throw new UnintentionalCodeFirstException();
            }

            public DbSet<T_SysLogs> T_SysLogs { get; set; }
            public DbSet<T_Wx_Menus> T_Wx_Menus { get; set; }
            public DbSet<T_FontIcons> T_FontIcons { get; set; }
            public DbSet<T_SysMenus> T_SysMenus { get; set; }
            public DbSet<T_SysUser> T_SysUser { get; set; }
            public DbSet<T_TextMessage> T_TextMessage { get; set; }
            public DbSet<T_ImgMessage> T_ImgMessage { get; set; }
        }
    }