//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_ImgMessage")]
    public partial class T_ImgMessage
    {
        [Key]
        public string MsgId { get; set; }
        public string MediaId { get; set; }
        public string FromUserName { get; set; }
        public string ToUserName { get; set; }
        public string MsgType { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> CreateTime { get; set; }
        public Nullable<System.DateTime> SysCreateTime { get; set; }
    }
}
