//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("T_XT_OperateLog")]
    public partial class T_XT_OperateLog
    {
        [Key]
        public string SysLogId { get; set; }
        public string SysContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
